[Batch: Availability and Validity]
owner = "gavofyork"
whitelist = []
matrix_room_id = "!wQXGIDhhJQSVXKqPwi:matrix.parity.io"

[Batch: Codebase Restructure]
owner = "gavofyork"
whitelist = []
matrix_room_id = "!wQXGIDhhJQSVXKqPwi:matrix.parity.io"

[Cumulus]
owner = "gavofyork"
whitelist = []
matrix_room_id = "!wQXGIDhhJQSVXKqPwi:matrix.parity.io"

